{
    'name': 'Dental Appointment',
    'version': '1.0',
    'summary': 'Dental Appointment Management',
    'category': 'Healthcare',
    'author': 'Antigravity',
    'depends': ['dental_base', 'dental_patient', 'dental_catalog', 'calendar', 'mail', 'resource', 'hr', 'hr_holidays'],
    'data': [
        'security/ir.access.csv',
        'data/ir_sequence_data.xml',
        'data/mail_template_data.xml',
        'views/appointment_type_views.xml',
        'views/appointment_views.xml',
        'views/waiting_list_views.xml',
        'views/recall_views.xml',
        'views/follow_up_views.xml',
        'views/res_partner_views.xml',
        'views/menu_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
